CREATE DATABASE SAS;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE, 
    name VARCHAR(255) NOT NULL, 
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    registration_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    participated_Surveys UUID[] DEFAULT '{}'
);